//
//  DetailsShopInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/15/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsShopBusinessLogic
{
    func getInfo(request: DetailsShop.Info.Request)
}

protocol DetailsShopDataStore
{
    var offer: OfferDAO? { get set }
}

class DetailsShopInteractor: DetailsShopBusinessLogic, DetailsShopDataStore
{
    
    
    var presenter: DetailsShopPresentationLogic?
    var worker: DetailsShopWorker?
    var offer: OfferDAO?
    
    // MARK: - getInfo
    
    func getInfo(request: DetailsShop.Info.Request)
    {
            let response = DetailsShop.Info.Response(offer: offer)
            presenter?.presentInfo(response: response)
        
    }
}
