//
//  DetailsShopModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/15/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias OfferDetailsCellType = DetailsShop.Info.ViewModel.CellType

enum DetailsShop
{
  // MARK: Use cases
  
  enum Info
  {
    struct Request
    {
    }
    struct Response
    {
        var offer : OfferDAO?
    }
    struct ViewModel
    {
        var offerEntries : [CellType]?
        var errorMsg : String?
        
        enum CellType {
            case header(OfferViewModel)
            case price(OfferViewModel)
            case text(OfferViewModel)
            case footer(OfferViewModel)
        }
    }
  }
}
