//
//  DetailsShopPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/15/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsShopPresentationLogic
{
  func presentInfo(response: DetailsShop.Info.Response)
}

class DetailsShopPresenter: DetailsShopPresentationLogic
{
  weak var viewController: DetailsShopDisplayLogic?
  
  // MARK: Do something
  
  func presentInfo(response: DetailsShop.Info.Response)
  {
    if let offer = response.offer {
        var OfferEntries = [OfferDetailsCellType]()
        
        let offerViewModel = OfferViewModel(model: offer, imageUrl: URL(string: offer.image), access: getAccessListAsString(accessList: offer.access))
        
        OfferEntries.append(OfferDetailsCellType.header(offerViewModel))
        OfferEntries.append(OfferDetailsCellType.text(offerViewModel))
        OfferEntries.append(OfferDetailsCellType.price(offerViewModel))
        OfferEntries.append(OfferDetailsCellType.text(offerViewModel))
        OfferEntries.append(OfferDetailsCellType.footer(offerViewModel))
        
        let viewModel = DetailsShop.Info.ViewModel(offerEntries: OfferEntries, errorMsg: nil)
        viewController?.displayInfo(viewModel: viewModel)
    } else {
        let viewModel = DetailsShop.Info.ViewModel(offerEntries: nil, errorMsg: "Un problème est survenu veuillez essayer plus trad!")
        viewController?.displayError(viewModel: viewModel)
    }
    
  }
    
    fileprivate func getAccessListAsString(accessList: [String]?) -> String {
        var accessStr = ""
        if let accessList = accessList {
            for access in accessList.enumerated() {
                accessStr = "\(accessStr)\(access.element)\((access.offset == accessList.count - 1) ? "" : ",")"
            }
        }
        return accessStr
    }
}
