//
//  PracticeInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 11/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PracticeBusinessLogic
{
    func getSubjects(request: Practice.Subjects.Request)
}

protocol PracticeDataStore
{
    //var name: String { get set }
}

class PracticeInteractor: PracticeBusinessLogic, PracticeDataStore
{
    var presenter: PracticePresentationLogic?
    var worker: PracticeWorker!
    
    // MARK: getTutors
    func getSubjects(request: Practice.Subjects.Request)
    {
        worker = PracticeWorker(mainPageStore: MainPageAPI())
        worker.getTopics { topics in
            guard let topicList = topics else {return}
            let subjectList = self.worker.getSubjectsFromTopicList(topicList: topicList)
            let response = Practice.Subjects.Response(subjects: subjectList)
            self.presenter?.presentSubjects(response: response)
        }
        
    }
    
}
