//
//  PracticePresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 11/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PracticePresentationLogic
{
  func presentSubjects(response: Practice.Subjects.Response)
}

class PracticePresenter: PracticePresentationLogic
{
  weak var viewController: PracticeDisplayLogic?
  
  // MARK: Do something
  
  func presentSubjects(response: Practice.Subjects.Response)
  {
    var subjectsViewModel = [String:Int]()
    
    for subject in response.subjects {
        subjectsViewModel[subject.name] = subject.objectId
    }
    
    let viewModel = Practice.Subjects.ViewModel(subjects: subjectsViewModel)
    viewController?.displaySubjects(viewModel: viewModel)
  }
}
