//
//  PracticeModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 11/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ModuleViewModel = Practice.Modules.ViewModel.ModuleViewModel

enum Practice
{
    // MARK: Use cases
    
    enum Subjects
    {
        struct Request
        {
        }
        struct Response
        {
            var subjects = [SubjectDAO]()
        }
        struct ViewModel
        {
            var subjects = [String:Int]()
        }
    }
    
    enum Modules
    {
        struct Request
        {
            var id : Int
        }
        struct Response
        {
            var modules = [ModuleDAO]()
        }
        struct ViewModel
        {
            struct ModuleViewModel {
                var model : TopicDAO
                var imageUrl : URL?
            }
            var modules = [ModuleViewModel]()
        }
    }
}
