//
//  LessonRouter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 12/21/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LessonRoutingLogic
{
    func routeToDetailQuiz(segue: UIStoryboardSegue?)
    func routeToVideoDetails(segue: UIStoryboardSegue?)
}

protocol LessonDataPassing
{
    var dataStore: LessonDataStore? { get }
}

class LessonRouter: NSObject, LessonRoutingLogic, LessonDataPassing
{
    weak var viewController: LessonViewController?
    var dataStore: LessonDataStore?
    
    // MARK: Routing
    
    func routeToDetailQuiz(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! QuizDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToQuizDetails(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "QuizDetails", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "QuizDetailsViewController") as! QuizDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToQuizDetails(source: dataStore!, destination: &destinationDS)
            navigateToQuizDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToVideoDetails(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! VideoDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToVideoDetails(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = VideoDetailsViewController()
            var destinationDS = destinationVC.router!.dataStore!
            passDataToVideoDetails(source: dataStore!, destination: &destinationDS)
            navigateToVideoDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToQuizDetails(source: LessonViewController, destination: QuizDetailsViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToVideoDetails(source: LessonViewController, destination: VideoDetailsViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToQuizDetails(source: LessonDataStore, destination: inout QuizDetailsDataStore)
    {
        destination.quiz = viewController?.selectedQuiz
    }
    
    func passDataToVideoDetails(source: LessonDataStore, destination: inout VideoDetailsDataStore)
    {
        let selectedRow = viewController?.tableView?.indexPathsForSelectedRows?[0].row
        let item = viewController?.items[selectedRow!]
        switch item {
        case .video(let viewModel):
            destination.url = viewModel.url
        default:
            break;
        }
        
    }
}
