//
//  LessonWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 12/21/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVKit

class LessonWorker
{
    
    func getQuizs(for chapter:ChapterDAO) -> [QuizDAO]
    {
        return chapter.quizs ?? [QuizDAO]()
    }
    
    func getVideos(for chapter: ChapterDAO) -> [VideoResponseAlias]
    {
        var videosResponse = [VideoResponseAlias]()
        if let videos = chapter.videos {
            for video in videos {
                var videoResponse = VideoResponseAlias()
                videoResponse.title = video.title
                videoResponse.provider = video.provider
                videoResponse.time = "1 hour ago"
                videoResponse.views = "78678"
                videoResponse.url = video.videoUrl
                
                videosResponse.append(videoResponse)
            }
        }
        return videosResponse
    }
}
