//
//  QuestionPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionPresentationLogic
{
  func presentSomething(response: Question.Something.Response)
}

class QuestionPresenter: QuestionPresentationLogic
{
  weak var viewController: QuestionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Question.Something.Response)
  {
    let viewModel = Question.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
