//
//  QuestionInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionBusinessLogic
{
    func getQuestionData(request: Question.ViewData.Request)
}

protocol QuestionDataStore
{
    var tutors: [TutorDAO]? { get set }
    var topics: [TopicDAO]? { get set }
    var tutor: TutorDAO? { get set }
}

class QuestionInteractor: QuestionBusinessLogic, QuestionDataStore
{
    var presenter: QuestionPresentationLogic?
    var worker: QuestionWorker?
    var tutorWorker: TutorListWorker?
    var tutors: [TutorDAO]?
    var topics: [TopicDAO]?
    var tutor: TutorDAO?
    
    // MARK: getQuestionData
    func getQuestionData(request: Question.ViewData.Request)
    {
        tutorWorker = TutorListWorker()
        var subjectList = [SubjectDAO]()
        if let topicList = self.topics {
            subjectList = tutorWorker?.getSubjectsFromTopicList(topicList: topicList) ?? [SubjectDAO]()
        }
        if let tutor = self.tutor {
            subjectList = tutor.subjects ?? [SubjectDAO]()
        }
        
        let response = Question.ViewData.Response(tutor: self.tutor, subjectList: subjectList)
        presenter?.presentQuestionData(response: response)
        
    }
}
