//
//  QuestionPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionPresentationLogic
{
    func presentQuestionData(response: Question.ViewData.Response)
    func presentChosenFile(response: Question.FileData.Response)
}

class QuestionPresenter: QuestionPresentationLogic
{
    weak var viewController: QuestionDisplayLogic?
    
    // MARK: presentQuestionData
    
    func presentQuestionData(response: Question.ViewData.Response)
    {
        var tutorViewModel : TutorViewModel?
        
        if let tutor = response.tutor {
            let subjects = getSubjectsString(for: tutor.subjects)
            let imageUrl = URL(string: tutor.picture ?? "")
            let answerdQuestions = getAnsweredQuestions(answersNbr: tutor.answredQuestions)
            tutorViewModel = TutorViewModel(model: tutor, subjects: subjects, answeredQuestions: answerdQuestions, imageUrl: imageUrl)
        }
        let viewModel = Question.ViewData.ViewModel(tutor: tutorViewModel, subjectList: response.subjectList ?? [SubjectDAO](), disableTutorSelection: response.disableTutorSelection)
        viewController?.displayQuestionData(viewModel: viewModel)
    }
    
    // MARK: presentChosenFile
    
    func presentChosenFile(response: Question.FileData.Response) {
        if let attachement = response.attachement {
            let viewModel = Question.FileData.ViewModel(attachement: attachement)
            viewController?.displayChosenFile(viewModel: viewModel)
        } else {
            let viewModel = Question.FileData.ViewModel(errorMsg: "Fichier ne peut pas être ajouter, notre équipe ont été informer de ce proplème")
            viewController?.displayChosenFileError(viewModel: viewModel)
        }
    }
    
}
