//
//  QuestionWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class QuestionWorker
{
    func getSubject(for questionSearched: QuestionDAO, from subjects: [TopicDAO]) -> TopicDAO?
    {
        // WTF is this shit worst shit i've ever written, fucked up APIs ... Shiiiiit
        for subject in subjects {
            for module in subject.modules ?? [] {
                for chapter in module.chapters ?? [] {
                    for quiz in chapter.quizs ?? [] {
                        for question in quiz.questions ?? [] {
                            if questionSearched.objectId == question.objectId {
                                return subject
                            }
                        }
                    }
                }
            }
        }
        return nil
    }
}
