//
//  QuestionInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/28/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionBusinessLogic
{
  func doSomething(request: Question.Something.Request)
}

protocol QuestionDataStore
{
  //var name: String { get set }
}

class QuestionInteractor: QuestionBusinessLogic, QuestionDataStore
{
  var presenter: QuestionPresentationLogic?
  var worker: QuestionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Question.Something.Request)
  {
    worker = QuestionWorker()
    worker?.doSomeWork()
    
    let response = Question.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
