//
//  TutorListPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TutorListPresentationLogic
{
  func presentSomething(response: TutorList.Something.Response)
}

class TutorListPresenter: TutorListPresentationLogic
{
  weak var viewController: TutorListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TutorList.Something.Response)
  {
    let viewModel = TutorList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
