//
//  TutorListInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TutorListBusinessLogic
{
    func getTutors(request: TutorList.Tutors.Request)
}

protocol TutorListDataStore
{
    var tutorList : [TutorDAO]? { get set }
}

class TutorListInteractor: TutorListBusinessLogic, TutorListDataStore
{
    var presenter: TutorListPresentationLogic?
    var worker: TutorListWorker?
    var tutorList : [TutorDAO]?
    
    // MARK: Do something
    
    func getTutors(request: TutorList.Tutors.Request)
    {
        if let tutorList = self.tutorList {
        let response = TutorList.Tutors.Response(tutorList: tutorList)
        presenter?.presentTutorList(response: response)
        }
    }
}
