//
//  TutorListInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TutorListBusinessLogic
{
    func getTutors(request: TutorList.Tutors.Request)
    func filterTutors(request: TutorList.FilterTutors.Request)
}

protocol TutorListDataStore
{
    var tutorList : [TutorDAO]? { get set }
    var topicList : [TopicDAO]? { get set }
    var isSelection : Bool! { get set }
}

class TutorListInteractor: TutorListBusinessLogic, TutorListDataStore
{
    var presenter: TutorListPresentationLogic?
    var worker: TutorListWorker!
    var tutorList : [TutorDAO]?
    var topicList : [TopicDAO]?
    var isSelection: Bool!
    
    // MARK: getTutors
    func getTutors(request: TutorList.Tutors.Request)
    {
        worker = TutorListWorker()
        if let tutorList = self.tutorList, let topicList = self.topicList {
            let subjectList = worker.getSubjectsFromTopicList(topicList: topicList)
            let response = TutorList.Tutors.Response(tutorList: tutorList,subjectsList: subjectList, isSelection: isSelection)
            presenter?.presentTutorList(response: response)
        }
    }
    
    // MARK: filterTutors
    func filterTutors(request: TutorList.FilterTutors.Request)
    {
        worker = TutorListWorker()
        if let tutorList = self.tutorList {
            let filtredTutorList = worker.filter(tutorList: tutorList, with: request.tutorName, and: request.subject)
            let response = TutorList.FilterTutors.Response(filtredTutorList: filtredTutorList)
            presenter?.presentFilteredTutorList(response: response)
        }
    }
}
