//
//  TutorListWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TutorListWorker
{
    func getSubjectsFromTopicList(topicList: [TopicDAO]) -> [SubjectDAO]
    {
        var subjects = [SubjectDAO]()
        for topic in topicList {
            let subject = SubjectDAO(objectId: topic.objectId, name: topic.title ?? "unknown subject")
            subjects.append(subject)
        }
        return subjects
    }
    
    func filter(tutorList:[TutorDAO], with name: String?, and subject: String?) -> [TutorDAO]
    {
        var filteredTutorList = tutorList
        
        if let name = name, name.count > 0 {
            filteredTutorList = filteredTutorList.filter { return $0.fullName.lowercased().contains(name.lowercased()) }
        }
        
        if let subject = subject {
            filteredTutorList = filteredTutorList.filter { return ($0.subjects!.contains { $0.name.lowercased() == subject.lowercased() }) }
        }
        return filteredTutorList
    }
}
