//
//  TutorListModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 10/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TutorList
{
    // MARK: Use cases
    
    enum Tutors
    {
        struct Request
        {
        }
        struct Response
        {
            var tutorList = [TutorDAO]()
            var subjectsList = [SubjectDAO]()
            var isSelection = false
        }
        struct ViewModel
        {
            var tutorList = [TutorViewModel]()
            var subjectsList = [Int:String]()
            var isSelection = false
        }
    }
    
    enum FilterTutors
    {
        struct Request
        {
            var subject : String?
            var tutorName : String?
        }
        struct Response
        {
            var filtredTutorList = [TutorDAO]()
        }
        struct ViewModel
        {
            var filtredTutorList = [TutorViewModel]()
        }
    }
}

struct TutorViewModel {
    
    var model : TutorDAO
    var subjects : String
    var answeredQuestions : NSAttributedString
    var imageUrl : URL?
}
