//
//  WelcomeInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 26/9/2021.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic
{
  func doSomething(request: Welcome.Something.Request)
}

protocol WelcomeDataStore
{
  //var name: String { get set }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore
{
  var presenter: WelcomePresentationLogic?
  var worker: WelcomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Welcome.Something.Request)
  {
    worker = WelcomeWorker()
    worker?.doSomeWork()
    
    let response = Welcome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
