//
//  AudioRecordPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 11/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioRecordPresentationLogic
{
  func presentSomething(response: AudioRecord.Something.Response)
}

class AudioRecordPresenter: AudioRecordPresentationLogic
{
  weak var viewController: AudioRecordDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AudioRecord.Something.Response)
  {
    let viewModel = AudioRecord.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
