//
//  AudioRecordInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 11/3/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioRecordBusinessLogic
{
  func doSomething(request: AudioRecord.Something.Request)
}

protocol AudioRecordDataStore
{
  //var name: String { get set }
}

class AudioRecordInteractor: AudioRecordBusinessLogic, AudioRecordDataStore
{
  var presenter: AudioRecordPresentationLogic?
  var worker: AudioRecordWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AudioRecord.Something.Request)
  {
    worker = AudioRecordWorker()
    worker?.doSomeWork()
    
    let response = AudioRecord.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
