//
//  StatsInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 25/9/2021.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatsBusinessLogic
{
    func fetchStats(request: Stats.Fetch.Request)
}

protocol StatsDataStore
{
    var currentUserInfo : CurrentUser? { get set }
}

class StatsInteractor: StatsBusinessLogic, StatsDataStore
{
    var presenter: StatsPresentationLogic?
    var worker: StatsWorker?
    
    // fetching this from profile VC
    var currentUserInfo : CurrentUser?
    
    // MARK: fetchStats
    
    func fetchStats(request: Stats.Fetch.Request)
    {
        let response = Stats.Fetch.Response(currentUserInfo: self.currentUserInfo)
        presenter?.presentStats(response: response)
    }
}
