//
//  StatsModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 25/9/2021.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias StatViewModel = Stats.Fetch.ViewModel.Item
typealias StatCellType = Stats.Fetch.ViewModel.CellType

enum Stats
{
    // MARK: Use cases
    
    enum Fetch
    {
        struct Request
        {
        }
        struct Response
        {
            var currentUserInfo : CurrentUser?
        }
        struct ViewModel
        {
            var statList : [StatCellType]?
            var errorMsg : String?
            
            struct Item {
                var title : String?
                var image : UIImage?
                var value : Int = 0
                var learningPathPerDays : [LearningPathPerDays]?
            }
            
            enum CellType {
                case chart(StatViewModel)
                case stat(StatViewModel)
            }
        }
    }
}
