//
//  StatsPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 25/9/2021.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatsPresentationLogic
{
    func presentStats(response: Stats.Fetch.Response)
}

class StatsPresenter: StatsPresentationLogic
{
    weak var viewController: StatsDisplayLogic?
    
    // MARK: Do something
    
    func presentStats(response: Stats.Fetch.Response)
    {
        if let stats = response.currentUserInfo?.statistics {
            var statList = [StatCellType]()
            // chart data
            statList.append(StatCellType.chart(StatViewModel(learningPathPerDays: stats.learningPathPerDays ?? [LearningPathPerDays]())))
            // 4 below elements data
            statList.append(StatCellType.stat(StatViewModel(title: "Questions résolues", image: UIImage(named: "solved-questions-icon"), value: stats.nbrSolvedQuestions )))
            statList.append(StatCellType.stat(StatViewModel(title: "Cours", image: UIImage(named: "courses-icon"), value: stats.nbrTakenCourses )))
            statList.append(StatCellType.stat(StatViewModel(title: "Quiz", image: UIImage(named: "quiz-icon"), value: stats.nbrFinishedQuiz )))
            statList.append(StatCellType.stat(StatViewModel(title: "heures totales", image: UIImage(named: "total-hour-icon"), value: stats.totalHours )))
            
            let viewModel = Stats.Fetch.ViewModel(statList: statList)
            viewController?.displayStats(viewModel: viewModel)
        } else {
            let errorMsg = "Service Indisponible, veuillez re-essayer ultérieurement"
            let viewModel = Stats.Fetch.ViewModel(errorMsg: errorMsg)
            viewController?.displayStatsError(viewModel: viewModel)
        }
    }
}
