//
//  UserProfileInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/17/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileBusinessLogic
{
    func getProfile(request: UserProfile.Profile.Request)
}

protocol UserProfileDataStore
{
    var tutorList : [TutorDAO]? { get set }
    var topicList : [TopicDAO]? { get set }
    var currentUserInfo : CurrentUser? { get set }
}

class UserProfileInteractor: UserProfileBusinessLogic, UserProfileDataStore
{
    var presenter: UserProfilePresentationLogic?
    var worker: UserWorker?
    
    // passing these data from home page (mainly to pass them along to fav tutors list scene)
    var tutorList: [TutorDAO]?
    var topicList: [TopicDAO]?
    
    // passing this to my learning path
    var currentUserInfo : CurrentUser?
    
    // MARK: getProfile
    func getProfile(request: UserProfile.Profile.Request)
    {
        worker = UserWorker(usersStore: UserAPI())
        worker?.fetchUserStats(completionHandler: { user in
            if let currentUser = user?.currentUser {
                self.currentUserInfo = currentUser
                let response = UserProfile.Profile.Response(user: currentUser)
                self.presenter?.presentProfile(response: response)
            } else {
                let response = UserProfile.Profile.Response(user: nil,errorMsg: "Service Indisponible instantanement, veuillez réessayer plus tard !")
                self.presenter?.presentProfile(response: response)
            }
        })
    }
}
