//
//  UserProfileModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/17/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ProfileCellType = UserProfile.Profile.ViewModel.CellType
typealias ProfileCellViewModel = UserProfile.Profile.ViewModel.Item

enum UserProfile
{
  // MARK: Use cases
  
  enum Profile
  {
    struct Request
    {
    }
    struct Response
    {
        var user : CurrentUser?
        var errorMsg : String?
    }
    struct ViewModel
    {
        var profileList : [CellType]?
        var errorMsg : String?
        
        struct Item {
            var title : String?
            var subtitle : String?
            var color : UIColor?
            
            var user : CurrentUser?
            var image : UIImage?
            
            var hasBigSeparator : Bool = false
            var hasSmallSeparator : Bool = false
            
            var value : Int = 1
            var total : Int = 1
            
        }
                
        enum CellType {
            case header(Item)
            case stat(Item)
            case simple(Item)
        }
    }
  }
}
