//
//  UserProfilePresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/17/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfilePresentationLogic
{
  func presentSomething(response: UserProfile.Something.Response)
}

class UserProfilePresenter: UserProfilePresentationLogic
{
  weak var viewController: UserProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserProfile.Something.Response)
  {
    let viewModel = UserProfile.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
