//
//  SubscribeViewController.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SubscribeDisplayLogic: class
{
    func displaySomething(viewModel: Subscribe.Something.ViewModel)
}

class SubscribeViewController: UIViewController, SubscribeDisplayLogic
{
    var interactor: SubscribeBusinessLogic?
    var router: (NSObjectProtocol & SubscribeRoutingLogic & SubscribeDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SubscribeInteractor()
        let presenter = SubscribePresenter()
        let router = SubscribeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    @IBAction func subscribe(_ sender: Any) {
    }
    
    @IBAction func login(_ sender: Any) {
        self.navigationController?.popViewController(animated: true)
    }
    func doSomething()
    {
        let request = Subscribe.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Subscribe.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
