//
//  SubscribeInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SubscribeBusinessLogic
{
  func doSomething(request: Subscribe.Something.Request)
}

protocol SubscribeDataStore
{
  //var name: String { get set }
}

class SubscribeInteractor: SubscribeBusinessLogic, SubscribeDataStore
{
  var presenter: SubscribePresentationLogic?
  var worker: SubscribeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Subscribe.Something.Request)
  {
    worker = SubscribeWorker()
    worker?.doSomeWork()
    
    let response = Subscribe.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
