//
//  SubscribeWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SubscribeWorker
{
    var workerDV = DataValidationWorker()
    
    func checkData(for request: Subscribe.User.Request) -> Bool
    {
        return workerDV.isValidEmail(request.email) && request.firstName.count > 0 && request.lastName.count > 0 && request.image.count > 35
            && workerDV.isValidPhoneNumber(request.phone) && request.password.count > 5 && request.password == request.passwordRepeat
    }
    
    func getErrorMessages(from request: Subscribe.User.Request, for response: inout Subscribe.User.Response) {
        if !workerDV.isValidEmail(request.email) {
            response.emailError = "Not a valid Email address"
        }
        if !(request.firstName.count > 0) {
            response.firstNameError = "Mandatory field"
        }
        if !(request.lastName.count > 0) {
            response.lastNameError = "Mandatory field"
        }
        if !(request.image.count > 35) {
            response.pictureError = "Please select a profile image"
        }
        if !workerDV.isValidPhoneNumber(request.phone) {
            response.phoneError = "Not a valid phone number"
        }
        if !(request.password.count > 5) {
            response.passwordError = "password doesn't fit criteria"
        }
        if request.password != request.passwordRepeat {
            response.passwordRepeatError = "Password confirmation doesn't match"
        }
    }
}
