//
//  SubscribePresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SubscribePresentationLogic
{
    func presentRegister(response: Subscribe.User.Response)
}

class SubscribePresenter: SubscribePresentationLogic
{
    weak var viewController: SubscribeDisplayLogic?
    
    // MARK: Do something
    
    func presentRegister(response: Subscribe.User.Response)
    {
        if let user = response.user {
            let viewModel = Subscribe.User.ViewModel.Result.Successfull(user: user)
            viewController?.displaySuccessfullRegister(viewModel: viewModel)
        } else {
            var viewModel = Subscribe.User.ViewModel.Result.Failure()
            if let errorMsg = response.errorMsg {
                viewModel.errorMsg = errorMsg
                viewController?.displayFailureRegister(viewModel: viewModel)
            } else {
                viewModel.emailError = response.emailError
                viewModel.firstNameError = response.firstNameError
                viewModel.lastNameError = response.lastNameError
                viewModel.phoneError = response.phoneError
                viewModel.pictureError = response.pictureError
                viewModel.passwordError = response.passwordError
                viewModel.passwordRepeatError = response.passwordRepeatError
                viewController?.displayFormError(viewModel: viewModel)
            }
        }
    }
}
