//
//  ShopInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/10/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopBusinessLogic
{
    func getOfferList(request: Shop.OfferList.Request)
}

protocol ShopDataStore
{
    //var name: String { get set }
}

class ShopInteractor: ShopBusinessLogic, ShopDataStore
{
    var presenter: ShopPresentationLogic?
    var worker: ShopWorker?
    //var name: String = ""
    
    // MARK: getOfferList
    
    func getOfferList(request: Shop.OfferList.Request)
    {
        worker = ShopWorker()
        worker?.getOffersList(completion: { (offersList) in
            let response = Shop.OfferList.Response(offersList: offersList)
            self.presenter?.presentOfferList(response: response)
        })
    }
}
