//
//  ShopWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/10/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShopWorker
{
    
    var shopStore : ShopStoreProtocol?
    
    
    init(shopStore: ShopStoreProtocol = ShopAPI()) {
        self.shopStore = shopStore
    }
    
    func getOffersList(completion: @escaping ([OfferDAO]?)->())
    {
        self.shopStore?.fetchOffersList(completionHandler: { (offerList) in
            do {
                let offersList = try offerList()
                completion(offersList)
            } catch {
                completion(nil)
            }
        })
    }
}

protocol ShopStoreProtocol {
    func fetchOffersList(completionHandler: @escaping (() throws -> [OfferDAO]) -> Void)
}
