//
//  ShopModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/10/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias OfferViewModel = Shop.OfferList.ViewModel.Offer
typealias OfferCellType = Shop.OfferList.ViewModel.CellType

enum Shop
{
  // MARK: Use cases
  
  enum OfferList
  {
    struct Request
    {
    }
    struct Response
    {
        var offersList : [OfferDAO]?
    }
    struct ViewModel
    {
        var offerList : [CellType]?
        var errorMsg : String?
        var hasSpecial = false
        
        struct Offer {
            var model : OfferDAO
            var imageUrl : URL?
            var access : String
        }
        
        enum CellType {
            case special(Offer)
            case simple(Offer)
        }
    }
  }
}
