//
//  ChatRatingWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/3/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChatRatingWorker
{
    
    var chatStore : ChatStoreProtocol
    
    init(chatStore: ChatStoreProtocol)
    {
        self.chatStore = chatStore
    }
    
    func rateChatWithTutor(tutorId: Int, questionId: Int, comment: String, rating: Int, compeltion: @escaping (Error?)->())
    {
        let request = RateTutorRequest(trainerId: tutorId, nbrStars: rating, message: comment, questionId: questionId)
        self.chatStore.submitChatRating(request: request) { (callback) in
            do {
                let _ = try callback()
                compeltion(nil)
            } catch {
                compeltion(error)
            }
        }
    }
}
