//
//  ChatRatingPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/3/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatRatingPresentationLogic
{
    func presentTutor(response: ChatRating.Tutor.Response)
    func presentSubmitRating(response: ChatRating.SubmitRating.Response)
}

class ChatRatingPresenter: ChatRatingPresentationLogic
{
    weak var viewController: ChatRatingDisplayLogic?
    
    // MARK: presentTutor
    
    func presentTutor(response: ChatRating.Tutor.Response)
    {
        let subjects = getSubjectsString(for: response.tutor.subjects)
        let pictureUrl = URL(string: response.tutor.picture ?? "")
        let viewModel = ChatRating.Tutor.ViewModel(tutor: response.tutor, subjects: subjects, pictureUrl: pictureUrl)
        viewController?.displayTutorInfo(viewModel: viewModel)
    }
    
    
    // MARK: present SubmitRating
    
    func presentSubmitRating(response: ChatRating.SubmitRating.Response) {
        if let error = response.error {
            let viewModel = ChatRating.SubmitRating.ViewModel(error: error)
            viewController?.displaySubmitRatingError(viewModel: viewModel)
        } else {
            let viewModel = ChatRating.SubmitRating.ViewModel(error: nil)
            viewController?.displaySubmitRating(viewModel: viewModel)
        }
    }
}
