//
//  ChatRatingModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 4/3/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChatRating
{
    // MARK: Use cases
    
    enum Tutor
    {
        struct Request
        {
        }
        struct Response
        {
            var tutor : TutorDAO
        }
        struct ViewModel
        {
            var tutor : TutorDAO
            var subjects : String
            var pictureUrl : URL?
        }
    }
    
    enum SubmitRating
    {
        struct Request
        {
            var rating : Int
            var comment : String
        }
        struct Response
        {
            var error : Error?
        }
        struct ViewModel
        {
            var error : Error?
        }
    }
}
