//
//  DiscussionRouter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 3/5/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DiscussionRoutingLogic
{
    func routeToChat(segue: UIStoryboardSegue?)
}

protocol DiscussionDataPassing
{
    var dataStore: DiscussionDataStore? { get }
}

class DiscussionRouter: NSObject, DiscussionRoutingLogic, DiscussionDataPassing
{
    weak var viewController: DiscussionViewController?
    var dataStore: DiscussionDataStore?
    
    // MARK: Routing
    
    func routeToChat(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ChatViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Chat", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChatViewController") as! ChatViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    
    func navigateToSomewhere(source: DiscussionViewController, destination: ChatViewController)
    {
        source.show(destination, sender: nil)
    }
    
    
    func passDataToSomewhere(source: DiscussionDataStore, destination: inout ChatDataStore)
    {
        let selectedRow = viewController?.tableView?.indexPathsForSelectedRows?[0].row
        let item = viewController?.discussionList[selectedRow!]
        
        destination.tutorId = item?.model.trainerId
        destination.discussionId = Int(item?.model.objectId ?? "0")
    }
}
