//
//  DiscussionModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 3/5/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias DiscussionViewModel = Discussion.List.ViewModel.Discussion

enum Discussion
{
    // MARK: Use cases
    
    // MARK:  - 1
    enum List
    {
        struct Request
        {
            var name : String?
        }
        struct Response
        {
            var discussions : [DiscussionDAO]?
            var tutors : [TutorDAO]?
        }
        struct ViewModel
        {
            var discussions = [Discussion]()
            
            struct Discussion {
                var url : URL?
                var tutor : TutorDAO?
                var model : DiscussionDAO
            }
        }
    }
    
    // MARK:  - 2
    enum Favorite
    {
        struct Request
        {
            var discussionId : String
            var isFavorite : Bool
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    // MARK:  - 3
    enum Delete
    {
        struct Request
        {
            var discussionId : String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
