//
//  ChatModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 2/28/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chat
{
    // MARK: Use cases
    
    enum Messages
    {
        struct Request
        {
        }
        struct Response
        {
            var messages: [MessageDAO] = []
            var tutor : TutorDAO
            var discussionId: Int
        }
        struct ViewModel
        {
            var messages: [Message] = []
            var tutor : TutorDAO
        }
    }
    
    enum SendMessage
    {
        struct Request
        {
            var id : Int
            var body : String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum SendAttachement
    {
        struct Request
        {
            var id : Int
            var images = [UIImage]()
            var attachements = [Attachement]()
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
