//
//  LoginModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: User Login
    
    enum User
    {
        struct Request
        {
            var email : String
            var password : String
        }
        struct Response
        {
            var user : UserDao?
        }
        struct ViewModel
        {
            enum Result
            {
                struct Successfull {
                    var name : String
                    var email : String
                }
                struct Failure {
                    var errorMsg : String
                }
            }
        }
    }
    
    // MARK: AutoFill data
    enum Users
    {
        struct Request
        {
        }
        struct Response
        {
            var users : [UserDao]?
        }
        struct ViewModel
        {
            var email : String
        }
    }
}
