//
//  LoginRouter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToHome(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToHome(segue: UIStoryboardSegue?)
    {
        if #available(iOS 13.0, *) {
            let storyboard = UIStoryboard(name: "Home", bundle: nil)
            let loginNavController = storyboard.instantiateViewController(identifier: "HomeTabBarController")
            
            
            (UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate)?.changeRootViewController(loginNavController)
        } else {
            // Fallback on earlier versions
        }
    }
    
    // MARK: Navigation
    
    func navigateToHome(source: LoginViewController, destination: UITabBarController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToHome(source: LoginDataStore, destination: inout HomeDataStore)
    {
        //destination.name = source.name
    }
}
