//
//  LoginViewController.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
    func displaySuccessfullLogin(viewModel: Login.User.ViewModel.Result.Successfull)
    func displayFailLogin(viewModel: Login.User.ViewModel.Result.Failure)
    func displayResetPasswordSuccess(viewModel: Login.ResetPassword.ViewModel)
    func displayResetPasswordFailure(viewModel: Login.ResetPassword.ViewModel)
    func displayAutoFillEmails(viewModel: Login.Users.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchAutoFillEmails()
        emailTextField.delegate = self
        pswTextField.delegate = self
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        registerForKeyboardNotifications()
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        deregisterFromKeyboardNotifications()
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    // MARK: IBOutlets
    
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var pswTextField: UITextField!
    @IBOutlet weak var errorEmailLabel: UILabel!
    @IBOutlet weak var errorPasswordLabel: UILabel!
    private var activeField: UITextField?
    
    // MARK: IBActions
    
    @IBAction func login(_ sender: Any) {
        loginUser()
    }
    
    @IBAction func forgotPassword(_ sender: Any) {
        let alert = UIAlertController(title: "Reset Password", message: "A Password reset email will be sent to the provided email address", preferredStyle: .alert)
        alert.addTextField {
            $0.placeholder = "your email address"
            $0.keyboardType = .emailAddress
            $0.addTarget(alert, action: #selector(alert.textDidChangeInResetPasswordAlert), for: .editingChanged)
        }

        alert.addAction(UIAlertAction(title: "Cancel", style: .destructive))
        
        let resetAction = UIAlertAction(title: "Reset Password", style: .default) { [unowned self] _ in
            guard let email = alert.textFields?[0].text else { return }
            self.resetPassword(for: email)
        }
        
        resetAction.isEnabled = false
        alert.addAction(resetAction)
        self.present(alert,animated: true)
    }
    // MARK: Login User
    
    func loginUser()
    {
        startAnimating(activityIndicator)
        let request = Login.User.Request(email: emailTextField.text!, password: pswTextField.text!)
        interactor?.loginUser(request: request)
    }
    
    func displaySuccessfullLogin(viewModel: Login.User.ViewModel.Result.Successfull)
    {
        stopAnimating(activityIndicator)
        router?.routeToHome(segue: nil)
    }
    
    func displayFailLogin(viewModel: Login.User.ViewModel.Result.Failure) {
        stopAnimating(activityIndicator)
        resetFormErrors()
        var hasFormError = false
        if let emailError = viewModel.emailError {
            setError(for: emailTextField, label: errorEmailLabel, text: emailError)
            hasFormError = true
        }
        if let passwordError = viewModel.passwordError {
            setError(for: pswTextField, label: errorPasswordLabel, text: passwordError)
            hasFormError = true
        }
        if !hasFormError {
            
            let alert = UIAlertController(title: "Error", message: viewModel.errorMsg, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: { (action) in
                alert.dismiss(animated: true, completion: nil)
            }))
            self.present(alert, animated: true)
        }
    }
    
    // MARK: Reset Password
    
    func resetPassword(for email: String) {
        startAnimating(activityIndicator)
        let request = Login.ResetPassword.Request(email: email)
        interactor?.resetPassword(request: request)
    }
    
    func displayResetPasswordSuccess(viewModel: Login.ResetPassword.ViewModel) {
        stopAnimating(activityIndicator)
        let alert = UIAlertController(title: "", message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: { (action) in
            alert.dismiss(animated: true, completion: nil)
        }))
        self.present(alert, animated: true)
    }
    
    func displayResetPasswordFailure(viewModel: Login.ResetPassword.ViewModel) {
        stopAnimating(activityIndicator)
        let alert = UIAlertController(title: "", message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: { (action) in
            alert.dismiss(animated: true) {
                self.forgotPassword(self)
            }
        }))
        self.present(alert, animated: true)
    }
    
    private func resetFormErrors() {
        pswTextField.layer.borderWidth = 0
        emailTextField.layer.borderWidth = 0
        errorPasswordLabel.text = ""
        errorEmailLabel.text = ""
    }
    // MARK: AutoFillEmails
    
    func fetchAutoFillEmails() {
        let request = Login.Users.Request()
        interactor?.fetchAutoFillEmails(request: request)
    }
    
    func displayAutoFillEmails(viewModel: Login.Users.ViewModel) {
        emailTextField.text = viewModel.email
    }
    
    
}
extension LoginViewController : UITextFieldDelegate {
    
    func registerForKeyboardNotifications(){
        //Adding notifies on keyboard appearing
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWasShown(notification:)), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillBeHidden(notification:)), name: UIResponder.keyboardWillHideNotification, object: nil)
    }
    
    func deregisterFromKeyboardNotifications(){
        //Removing notifies on keyboard appearing
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification, object: nil)
    }
    
    @objc func keyboardWasShown(notification: NSNotification){
        //Need to calculate keyboard exact size due to Apple suggestions
        self.scrollView.isScrollEnabled = true
        let info = notification.userInfo!
        let keyboardSize = (info[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue.size
        let contentInsets : UIEdgeInsets = UIEdgeInsets(top: 0.0, left: 0.0, bottom: keyboardSize!.height, right: 0.0)
        
        self.scrollView.contentInset = contentInsets
        self.scrollView.scrollIndicatorInsets = contentInsets
        
        var aRect : CGRect = self.view.frame
        aRect.size.height -= keyboardSize!.height
        if let activeField = self.activeField {
            if (!aRect.contains(activeField.frame.origin)){
                self.scrollView.scrollRectToVisible(activeField.frame, animated: true)
            }
        }
    }
    
    @objc func keyboardWillBeHidden(notification: NSNotification){
        //Once keyboard disappears, restore original positions
        self.scrollView.contentInset = UIEdgeInsets.zero
        self.scrollView.scrollIndicatorInsets = UIEdgeInsets.zero
        self.view.endEditing(true)
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField){
        activeField = textField
    }
    
    func textFieldDidEndEditing(_ textField: UITextField){
        activeField = nil
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        // Try to find next responder
        if let nextField = textField.superview?.viewWithTag(textField.tag + 1) as? UITextField {
            nextField.becomeFirstResponder()
        } else {
            // Not found, so remove keyboard.
            textField.resignFirstResponder()
        }
        // Do not add a line break
        return false
    }
}
extension UINavigationController {
    open override var preferredStatusBarStyle: UIStatusBarStyle {
        return topViewController?.preferredStatusBarStyle ?? .default
    }
}
