//
//  LoginPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentLoginUser(response: Login.User.Response)
    func presentAutoFillEmails(response: Login.Users.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentLoginUser(response: Login.User.Response)
    {
        
        if let user = response.user {
            let loggedUser = Login.User.ViewModel.Result.Successfull(name: user.currentUser.firstName+" "+user.currentUser.lastName, email: user.currentUser.email)
            viewController?.displaySuccessfullLogin(viewModel: loggedUser)
        }
        else {
            let loginError = Login.User.ViewModel.Result.Failure(errorMsg: "Wrong email or Password please retry !")
            viewController?.displayFailLogin(viewModel: loginError)
        }
    }
    
    func presentAutoFillEmails(response: Login.Users.Response)
    {
        let email = response.users?.last?.currentUser.email ?? ""
        let viewModel = Login.Users.ViewModel(email: email)
        viewController?.displayAutoFillEmails(viewModel: viewModel)
    }
}
