//
//  LoginInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func loginUser(request: Login.User.Request)
    func fetchAutoFillEmails(request: Login.Users.Request)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    func fetchAutoFillEmails(request: Login.Users.Request) {
        worker.fetchAllUsers(completionHandler: { (users) in
            let response = Login.Users.Response(users: users)
            self.presenter?.presentAutoFillEmails(response: response)
        })
    }
    
    var presenter: LoginPresentationLogic?
    var worker = UserWorker(usersStore: UserCoreDataStore())
    //var name: String = ""
    
    // MARK: Do something
    
    func loginUser(request: Login.User.Request) {
        worker.fetchUserForLogin(email: request.email, completionHandler: { (user) in
            let response = Login.User.Response(user: user)
            self.presenter?.presentLoginUser(response: response)
        })
    }
}
