//
//  LoginInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func loginUser(request: Login.User.Request)
    func fetchAutoFillEmails(request: Login.Users.Request)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    func fetchAutoFillEmails(request: Login.Users.Request) {
        worker.fetchAllUsers(completionHandler: { (users) in
            let response = Login.Users.Response(users: users)
            self.presenter?.presentAutoFillEmails(response: response)
        })
    }
    
    var presenter: LoginPresentationLogic?
    var worker = UserWorker(usersStore: UserCoreDataStore())
    var workerApi = UserWorker(usersStore: UserAPI())
    var workerDataValidation = DataValidationWorker()
    
    // MARK: Login User
    
    func loginUser(request: Login.User.Request) {
        
        if let response = validateLoginRequest(request: request) {
            self.presenter?.presentLoginUser(response: response)
        } else {
            workerApi.loginUser(loginRequest:request , completionHandler: { userResponse in
                let response = Login.User.Response(user: userResponse)
                self.presenter?.presentLoginUser(response: response)
            })
        }
    }
    
    private func validateLoginRequest(request: Login.User.Request) -> Login.User.Response? {
        var response : Login.User.Response?
        if !workerDataValidation.isValidEmail(request.email) {
            response = Login.User.Response(emailError: "Please insert a valid email adress")
        }
        if request.password.count < 1 {
            response = Login.User.Response(emailError: response?.emailError, passwordError: "Please insert your password")
        }
        return response
    }
}
