//
//  VideoDetailsWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 2/14/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class VideoDetailsWorker
{
    func getVideoUrl(from videoUrl: URL?) -> URL?
    {
        var youtubeId = ""
        
        if let originalUrl = videoUrl {
            youtubeId = originalUrl.lastPathComponent
        }
        
        return URL(string: "https://www.youtube.com/embed/\(youtubeId)?playsinline=1?autoplay=1")
    }
}
