//
//  VideoDetailsInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 2/14/21.
//  Copyright (c) 2021 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoDetailsBusinessLogic
{
    func getVideoData(request: VideoDetails.Load.Request)
}

protocol VideoDetailsDataStore
{
    var url: URL? { get set }
}

class VideoDetailsInteractor: VideoDetailsBusinessLogic, VideoDetailsDataStore
{    
    var presenter: VideoDetailsPresentationLogic?
    var worker: VideoDetailsWorker?
    var url: URL?
    
    // MARK: getVideoData
    
    func getVideoData(request: VideoDetails.Load.Request)
    {
        worker = VideoDetailsWorker()
        let url = worker?.getVideoUrl(from: self.url)
        
        let response = VideoDetails.Load.Response(videoUrl: url)
        presenter?.presentVideoData(response: response)
    }
}
