//
//  SplashInteractorTests.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 5/1/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import AcaBase
import XCTest

class SplashInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: SplashInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupSplashInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSplashInteractor()
  {
    sut = SplashInteractor()
  }
  
  // MARK: Test doubles
  
  class SplashPresentationLogicSpy: SplashPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Splash.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = SplashPresentationLogicSpy()
    sut.presenter = spy
    let request = Splash.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
