//
//  TutorWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 9/27/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TutorWorker
{
    var tutorStore : TutorStoreProtocol
    
    init(tutorStore: TutorStoreProtocol)
    {
        self.tutorStore = tutorStore
    }
    
    func addToFavorites(id: Int,completionHandler: @escaping (String) -> Void)
    {
        let request = FavoriteRequest(trainerId: id)
        self.tutorStore.addToFavorites(request: request) { (response: () throws -> FavoriteResponse) in
            do {
                let _ = try response()
                DispatchQueue.main.async {
                    completionHandler("Tuteur ajouté au favoris")
                }
            } catch {
                let nserror = error as NSError
                print("Unresolved error \(nserror), \(nserror.userInfo)")
                DispatchQueue.main.async {
                    completionHandler("Un problème est survenu veuillez réessayer plus tard")
                }
            }
        }
    }
}
protocol TutorStoreProtocol {
    func addToFavorites(request: FavoriteRequest, completionHandler: @escaping (() throws -> FavoriteResponse) -> Void)
}
