//
//  TutorPresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 9/27/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TutorPresentationLogic
{
    func presentTutor(response: Tutor.Display.Response)
    func presentFavorite(response: Tutor.Favorite.Response)
}

class TutorPresenter: TutorPresentationLogic
{
    weak var viewController: TutorDisplayLogic?
    
    // MARK: presentTutor
    func presentTutor(response: Tutor.Display.Response)
    {
        let tutor = response.tutor
        let subjects = getSubjectsString(for: tutor?.subjects)
        let pictureUrl = URL(string: tutor?.picture ?? "")
        let viewModel = Tutor.Display.ViewModel(tutor: response.tutor,pictureUrl: pictureUrl,subjects: subjects)
        
        viewController?.displayTutor(viewModel: viewModel)
    }
    
    // MARK: presentFavorite
    func presentFavorite(response: Tutor.Favorite.Response) {
        let viewModel = Tutor.Favorite.ViewModel(message: response.message, isFav: response.isFav)
        
        viewController?.displayFavorite(viewModel: viewModel)
    }
}
