//
//  HomeModels.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum Tutors
    {
        struct Request
        {
        }
        struct Response
        {
            var tutors = [TutorDAO]()
        }
        struct ViewModel
        {
            var tutorList = [TutorViewModel]()
            var errorMsg : String?
        }
    }
    
    enum Topics
    {
        struct Request
        {
        }
        struct Response
        {
            var topics : [TopicDAO]?
        }
        struct ViewModel
        {
            var topics : [TopicDAO]
            var errorMsg : String?
        }
    }
    
    enum Quizs
    {
        struct Request
        {
        }
        struct Response
        {
            var quizs : [QuizDAO]?
        }
        struct ViewModel
        {
            var quizs : [QuizDAO]
            var errorMsg : String?
        }
    }
    
    enum Videos
    {
        struct Request
        {
        }
        struct Response
        {
            var videoList = [VideoResponseAlias]()
        }
        struct ViewModel
        {
            var videoList = [VideoAlias]()
        }
    }
}
