//
//  HomeInteractor.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getTrainers(request: Home.Tutors.Request)
    func getTopics(request: Home.Topics.Request)
}

protocol HomeDataStore
{
    var tutors: [TutorDAO]? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var workerApi = HomeWorker(mainPageStore: MainPageAPI())
    var tutors: [TutorDAO]?
    
    // MARK: HomeBusinessLogic Stubs
    
    func getTrainers(request: Home.Tutors.Request)
    {
        workerApi.getTutors { (tutors) in
            self.tutors = tutors
            let response = Home.Tutors.Response(tutors:tutors )
            self.presenter?.presentTrainers(response: response)
        }
    }
    
    func getTopics(request: Home.Topics.Request) {
        workerApi.getTopics { topics in
            let response = Home.Topics.Response(topics: topics )
            self.presenter?.presentTopics(response: response)
        }
    }
}
