//
//  HomeViewController.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class
{
    func displayTrainers(viewModel: Home.Tutors.ViewModel)
    func displayTopics(viewModel: Home.Topics.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic
{
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    var offset = CGFloat()
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: 🔌 IBOutlets
    
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var topicCollectionView: UICollectionView!
    
    // MARK: Properties
    
    var trainers = [TutorDAO]()
    var topics = [TopicDAO]()
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        self.navigationController?.navigationBar.shadowImage = UIImage()
        scrollView.delegate = self
        getTrainers()
        getTopics()
        self.setNeedsStatusBarAppearanceUpdate()
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .darkContent
    }
    
    override func viewWillAppear(_ animated: Bool) {
        
        if let navigationBar = self.navigationController?.navigationBar {
            let navBarAppearance = UINavigationBarAppearance()
            // bar appearance making navbar not transparent
            navigationBar.standardAppearance = navBarAppearance
            navigationBar.scrollEdgeAppearance = navBarAppearance
            navigationBar.compactAppearance = navBarAppearance
            navigationBar.barStyle = .default
            navigationBar.prefersLargeTitles = false
            navigationBar.setBackgroundImage(UIImage(), for: .default)
            navigationBar.shadowImage = UIImage()
            
        }
        self.setHomePageNavBar(for: self.navigationItem, titleViewOpacity: offset)
        navbarAnimation()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        navbarAnimation()
    }
    // MARK: Actions
    
    @objc func clickTitleButton() {
        print("clickTitleButton")
    }
    
    @objc func clickRightButton() {
        print("clickRightButton")
        router?.routeToLogin(segue: nil)
    }
    
    @objc func clickLeftButton() {
        print("clickLeftButton")
    }
    
    // MARK: ✅ Interactor Calls
    
    
    // MARK: get Trainers
    func getTrainers()
    {
        let request = Home.Tutors.Request()
        interactor?.getTrainers(request: request)
    }
    
    func displayTrainers(viewModel: Home.Tutors.ViewModel)
    {
        //nameTextField.text = viewModel.name
        trainers = viewModel.tutors
        self.collectionView.reloadData()
    }
    
    // MARK: get Topics
    
    func getTopics() {
        let request = Home.Topics.Request()
        interactor?.getTopics(request: request)
    }
    
    func displayTopics(viewModel: Home.Topics.ViewModel) {
        topics = viewModel.topics
        self.topicCollectionView.reloadData()
    }
    
    // MARK: Private functions
    
    private func navbarAnimation(){
        if offset > 1 {
            offset = 1
            navigationItem.leftBarButtonItem?.customView?.alpha = 1
            navigationItem.rightBarButtonItem?.customView?.alpha = 1
            navigationItem.titleView?.alpha = 1
            navigationController?.navigationBar.backgroundColor = UIColor(white: 1, alpha: 1)
            self.navigationController?.navigationBar.layer.masksToBounds = false
            self.navigationController?.navigationBar.layer.shadowColor = UIColor.lightGray.cgColor
            self.navigationController?.navigationBar.layer.shadowOpacity = 0.8
            self.navigationController?.navigationBar.layer.shadowOffset = CGSize(width: 0, height: 2.0)
            self.navigationController?.navigationBar.layer.shadowRadius = 1
        } else {
            navigationItem.leftBarButtonItem?.customView?.alpha = offset
            navigationItem.rightBarButtonItem?.customView?.alpha = offset
            navigationItem.titleView?.alpha = offset
            self.navigationController?.navigationBar.alpha = offset
            navigationController?.navigationBar.backgroundColor = UIColor(white: 1, alpha: offset)
        }
    }
}
extension HomeViewController: UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if topicCollectionView == collectionView {
            return (topics.count > 3) ? 4 : 0
        }
        return (trainers.count > 3) ? 4 : 0
    }
    
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if topicCollectionView == collectionView {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "topicCell", for: indexPath) as! TopicCell
            cell.set(viewModel: topics[indexPath.row])
            return cell
        }
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "teacherCell", for: indexPath) as! TrainerCell
        cell.set(trainer: trainers[indexPath.row])
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize
    {
        if topicCollectionView == collectionView {
            return CGSize(width: 160.0, height: 150.0)
        }
        return CGSize(width: 128.0, height: 142.0)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        performSegue(withIdentifier: "DetailTutor", sender: self)
    }
}

// MARK: Navigation Bar Animation
extension HomeViewController: UIScrollViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        self.offset = self.scrollView.contentOffset.y / 150
        self.navbarAnimation()
    }
}
