//
//  HomeWorker.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    
    var mainPageStore : MainPageStoreProtocol
    
    init(mainPageStore: MainPageStoreProtocol)
    {
        self.mainPageStore = mainPageStore
    }
    
    func getTutors(completionHandler: @escaping ([TutorDAO]?) -> Void) {
        self.mainPageStore.fetchTrainers() { (trainers: () throws -> [TutorDAO]) -> Void in
            do {
                let trainers = try trainers()
                DispatchQueue.main.async {
                    completionHandler(trainers)
                }
            } catch {
                let nserror = error as NSError
                print("Unresolved error \(nserror), \(nserror.userInfo)")
                DispatchQueue.main.async {
                    completionHandler(nil)
                }
            }
        }
    }
    
    func getTopics(completionHandler: @escaping ([TopicDAO]?) -> Void) {
        self.mainPageStore.fetchTopics { (topics: () throws -> [TopicDAO]) in
            do {
                let topics = try topics()
                DispatchQueue.main.async {
                    completionHandler(topics)
                }
            } catch {
                let nserror = error as NSError
                print("Unresolved error \(nserror), \(nserror.userInfo)")
                DispatchQueue.main.async {
                    completionHandler(nil)
                }
            }
        }
    }
}
