//
//  HomePresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentTrainers(response: Home.Tutors.Response)
    func presentTopics(response: Home.Topics.Response)
    func presentQuizs(response: Home.Quizs.Response)
    func presentHomeVideos(response: Home.Videos.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: presentTrainers
    func presentTrainers(response: Home.Tutors.Response)
    {
        var tutorViewModels = [TutorViewModel]()
        
        for tutor in response.tutors {
            let subjects = getSubjectsString(for: tutor.subjects)
            let imageUrl = URL(string: tutor.picture ?? "")
            let answerdQuestions = getAnsweredQuestions(answersNbr: tutor.answredQuestions)
            let tutor = TutorViewModel(model: tutor, subjects: subjects, answeredQuestions: answerdQuestions, imageUrl: imageUrl)
            tutorViewModels.append(tutor)
        }
        
        let viewModel = Home.Tutors.ViewModel(tutorList: tutorViewModels, errorMsg: "error fetching trainers")
        viewController?.displayTrainers(viewModel: viewModel)
        
    }
    
    // MARK: presentTopics
    func presentTopics(response: Home.Topics.Response) {
        let viewModel = Home.Topics.ViewModel(topics: response.topics ?? [TopicDAO](), errorMsg: "error fetching trainers")
        viewController?.displayTopics(viewModel: viewModel)
    }
    
    // MARK: presentQuizs
    func presentQuizs(response: Home.Quizs.Response) {
        let viewModel = Home.Quizs.ViewModel(quizs: response.quizs ?? [QuizDAO](), errorMsg: "error fetching quizs")
        viewController?.displayQuizs(viewModel: viewModel)
    }
    
    // MARK: presentVideos
    func presentHomeVideos(response: Home.Videos.Response) {
        var videosViewModel = [VideoAlias]()
        for video in response.videoList {
            var videoItem = VideoAlias()
            videoItem.title = video.title ?? "Video sans titre"
            videoItem.provider = video.provider ?? "Video sans tuteur"
            videoItem.views = video.views ?? "100"
            videoItem.time = video.time ?? "il y a 1 min"
            videoItem.url = URL(string: video.url ?? "")
            videosViewModel.append(videoItem)
        }
        let viewModel = Home.Videos.ViewModel(videoList: videosViewModel)
        viewController?.displayHomeVideos(viewModel: viewModel)
    }
}
