//
//  HomePresenter.swift
//  AcaBase
//
//  Created by Seif eddinne meddeb on 6/14/20.
//  Copyright (c) 2020 Seif eddinne meddeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentTrainers(response: Home.Trainers.Response)
    func presentTopics(response: Home.Topics.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentTrainers(response: Home.Trainers.Response)
    {
        let viewModel = Home.Trainers.ViewModel(trainers: response.trainers ?? [TrainerDAO](), errorMsg: "error fetching trainers")
        viewController?.displayTrainers(viewModel: viewModel)
        
    }
    
    func presentTopics(response: Home.Topics.Response) {
        let viewModel = Home.Topics.ViewModel(topics: response.topics ?? [TopicDAO](), errorMsg: "error fetching trainers")
        viewController?.displayTopics(viewModel: viewModel)
    }
}
